---
title: "MySQL notes"
output: html_document
date: "2022-12-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## MySQL notes

Query the list of CITY names ending with vowels (a, e, i, o, u) from STATION. Your result cannot contain duplicates.

```{}
SELECT DISTINCT CITY FROM STATION WHERE REGEXP_LIKE(LOWER(CITY), '.*[aeiou]$');
```

Query the list of CITY names from STATION which have vowels (i.e., a, e, i, o, and u) as both their first and last characters. Your result cannot contain duplicates.

```{}
SELECT CITY FROM STATION WHERE REGEXP_LIKE(LOWER(CITY), '^[aeiou].*[aeiou]$');
```

Query the list of CITY names from STATION that do not start with vowels. Your result cannot contain duplicates.

```{}
SELECT DISTINCT CITY FROM STATION WHERE REGEXP_LIKE(LOWER(CITY), '^[^aeiou].*');
```

Query the list of CITY names from STATION that do not end with vowels. Your result cannot contain duplicates.

```{}
SELECT DISTINCT CITY FROM STATION WHERE REGEXP_LIKE(LOWER(CITY), '.*[^aeiou]$');
```

Query the list of CITY names from STATION that either do not start with vowels or do not end with vowels. Your result cannot contain duplicates.

```{}
SELECT DISTINCT CITY FROM STATION WHERE REGEXP_LIKE(LOWER(CITY), '(^[^aeiou].*)|(.*[^aeiou]$)');
```

Query the list of CITY names from STATION that do not start with vowels and do not end with vowels. Your result cannot contain duplicates.

```{}
SELECT DISTINCT CITY FROM STATION WHERE REGEXP_LIKE(LOWER(CITY), '^[^aeiou].*[^aeiou]$');
```

Query the Name of any student in STUDENTS who scored higher than Marks. Order your output by the last three characters of each name. If two or more students both have names ending in the same last three characters.

```{}
SELECT NAME FROM STUDENTS WHERE Marks > 75 ORDER BY RIGHT(Name, 3), ID;
```

Write a query that prints a list of employee names (i.e.: the name attribute) from the Employee table in alphabetical order.

```{}
SELECT name FROM Employee ORDER BY name;
```

Write a query that prints a list of employee names (i.e.: the name attribute) for employees in Employee having a salary greater than per month who have been employees for less than months. Sort your result by ascending employee_id.

```{}
SELECT name FROM Employee WHERE salary > 2000 AND months < 10 ORDER BY employee_id;
```


